#! /bin/bash
echo hello world. Downloading Inc 5000 data....
for (( y=2010; y <= 2012; y++))
do
	let year=$y
	curl -is "http://www.inc.com/inc5000/list/$year" > temp.txt
	PAGE_COUNT=$(awk -f get_pagecount.awk temp.txt)
	echo Found $PAGE_COUNT pages to parse for $year... Get crack\'n boy!
	rm "list_$year.csv"
	for (( c=1; c <= $PAGE_COUNT; c++))
	do
		let url_end=$[($c*100)-100]
		echo "[Page $c of $PAGE_COUNT] ->"
		curl -is "http://www.inc.com/inc5000/list/$year/$url_end//" > temp.txt
		perl process_inc5000.pl temp.txt $url_end $year
	done
done